### PR TITLE
Issue 51

### PR DESCRIPTION
**Pull request by coverney**
Added a potential fix to 51 for ```plot_inducer_characterization.m```. I would like to get some advice on my approach. Basically, I do not call ZeroOnLog unless I obtain a min_value of less than or equal to 0. The tests I have do not seem to have a min_value that small, so I can not test out the results. I found a way to make the ZeroOnLog plots look nicer, but I am still not sure what the zero and start should be. For now, they will start at 0 and go to the smallest non_zero value.

```
if min_value <= 0
ZeroOnLog(0,min_non_zero);
end

### CODE REVIEW

**Comment by jakebeal** [comment]
Even though data for the tests didn't have a value that small, you can tell them that the input was zero anyway. :-)

With regards to the range: you aren't calling it correctly: `ZeroOnLog(0,min_non_zero)` will not know where to put the zero, since it wasn't on the log scale.  I would suggest instead: `ZeroOnLog(min_non_zero/10,min_non_zero)`

**Comment by coverney** [comment]
I set the min_value to 0 to see how the graph would look, but the break is right on top of the y-axis. I am trying to play around with the ZeroOnLog function to extend the x-axis, so the zero does not get cut off.

**Comment by coverney** [comment]
I edited the ZeroOnLog function and will rename my edited version as ZeroOnLogX

**Comment by coverney** [comment]
fine-dox-mean
This is an example of a ZeroOnLog plot. There are no actual zero values due to the template data, but I am not sure why the break is not in the middle of the zerotick and mintick even though the code should place the break in the middle.

**Comment by jakebeal** [comment]
Hmm... that's definitely not working correctly.  The output should look more like this (only on the X axis rather than Y):
tmp_obscured

**Comment by coverney** [comment]
That does look much better. Do you know where I can find the code for that example?

**Comment by jakebeal** [comment]
It's unpublished material, so I won't post the full code, but the important bits are:
1. Set all the zeros in the dataset to 2e-4
2. `ylim([1e-4 1]);
ZeroOnLogY(2e-4,1e-3);`

**Comment by coverney** [comment]
Thank you! I think I know how to fix it now. I will go back to it after fixing the plot_plusminus_comparison graphs.

**Comment by coverney** [comment]
I was able to get the ZeroOnLog plot to output the graph below. I was wondering if this is sufficient. Also, I would be adding the ZeroOnLog function call on ```plot_inducer_characterization``` and ```plot_population_inducer_characterization```. Are there any other plotting functions that need this feature?
fine-dox-mean

**Comment by coverney** [comment]
For 1, is this just a personal test to see if it works or should something be included in any of the test files?

**Comment by coverney** [comment]
When I set one of the inducer levels to 0 I got this: 
```inducer_levels(2) = 0;```
fine-dox-mean

**Pull request merged**
