### PR TITLE
Added test_colormodel_csv

### PR DESCRIPTION
**Pull request by coverney**

### CODE REVIEW

**Comment by coverney** [comment]
I am getting this warning with Travis
```warning: MEFL units are recommended, rather than MEPTR```
but when I test it locally on Octave, I can not replicate this problem.

**Comment by jakebeal** [comment]
I believe this warning is expected. You can just drop the test, though, if
it is one of the news ones: we don't need to test all the permutations of
the color model, just that a typical run can use CSV correctly.

Thanks,
-Jake
(sent from my phone)

**Comment by coverney** [comment]
Sounds good! Then I will remove the warnings and check for units.

**Comment by coverney** [comment]
I am pretty stumped. The basic ```test_colormodel_csv_endtoend``` function is not working in Travis but works perfectly fine locally. Even after commenting out the channel name comparison, now I am getting different values for```UT.k_ERF```.

**Comment by jakebeal** [comment]
I'll take a pass in a couple of days and see if I can sort it out then.

**Comment by coverney** [comment]
Great! Thank you very much! I can also try to take another look at in tomorrow morning

**Comment by coverney** [comment]
I think the problem has something to do with MEPTR vs MEFL units. Can we force MEFL units to be calculated with a TASBEConfig (i.e. ```doc.calibration.overrideUnits```)?

**Comment by jakebeal** [comment]
I don't think that's the problem any more --- the current error is in test_colormodel_csv_endtoend on line  instead.

**Comment by coverney** [comment]
I took another look at the Travis log and within `test_colormodel_csv_endtoend`, there is the warning: `warning: MEFL units are recommended, rather than MEPTR`. That warning doesn't appear in the corresponding non-CSV test. However, the warning does appear in the other non-CSV colormodel tests (i.e. singlered), and it just remains for the CSV tests. Is it possible that the non-CSV tests turn on a config that remains on when `test_colormodel_csv_endtoend` is running?

**Comment by jakebeal** [comment]
I've managed to reproduce the error locally, and it does appear to be related to some sort of cross-test configuration contamination.  I'll get it from here.

**Comment by coverney** [comment]
Makes sense! Thank you for letting me know!

**Comment by jakebeal** [comment]
Sorted!

**Pull request merged**
