### PR TITLE
Addressed issues #397 and #398

### PR DESCRIPTION
**Pull request by coverney**

### CODE REVIEW

**Comment by coverney** [comment]
I am getting this error:
```
failure: inputs are not of the same size
First input: 1x18 char
'UnusuallySmallFile'
Second input: 1x13 char
'TooManyEvents'
```
Even though I tested the branch individually and it was fine. Once I fixed a merge conflict, it didn't work anymore. I am not sure how to address this.

**Comment by jakebeal** [comment]
This looks like something's injecting an extra warning that was not there before.  Maybe it's the directory creation notice from writing the header?

**Comment by coverney** [comment]
The number of events is 170439 which is less than 1e8

**Comment by coverney** [comment]
I think it is coming from:
```
data = rawfcs;
    n_raw_events = size(data,1);
    if n_raw_events<TASBEConfig.get('flow.smallFileWarning')
        display(n_raw_events);
        TASBESession.warn('TASBE:ReadFCS','UnusuallySmallFile','FCS file "%s" is unusually small: only %i events', filename, n_raw_events);
    end
```
within ```read_filtered_au```

**Comment by jakebeal** [comment]
Right: the failing test file is trying to generate those errors, in order to validate that the warning thresholds are working.  This is what would happen if your merge conflict fix accidentally deleted the "file too large" warning check.

**Comment by coverney** [comment]
How do I fix that then? Can I undo a merge conflict resolution?

**Comment by coverney** [comment]
I copied the original file back in. Should I reset the flow.smallFileWarning value in the test_fcs_too_large function so the UnusuallySmallFile warning won't be present?

**Comment by jakebeal** [comment]
The problem isn't the test file --- that hasn't changed.  I think the problem is in how you're calling fca_readfcs, so that it's not getting passed the optional argument any more.  I checked and found that appears to be so, and have pushed a patch that I think will fix this.

**Comment by coverney** [comment]
I see! That makes sense!

**Pull request merged**
