### PR TITLE
Addressed issue 415

### PR DESCRIPTION
**Pull request by coverney**

### CODE REVIEW

**Comment by jakebeal** [comment]
Can you please also add a "round trip" test that checks to make sure the the CSV header that you write matches the CSV header that you read?

**Comment by coverney** [comment]
I was thinking of adding a test like that after implementing the datafile object because currently, I don't have any tests that read in CSV files, runs a batch analysis, and writes a new JSON header. The tutorial has one though.

**Comment by coverney** [comment]
Would it be fine if I add that test to the tutorial for now?

**Comment by jakebeal** [comment]
I think we'll need this test in the main project sooner rather than later, because the SD2 folks are planning to start using CSV-reading soon.

**Comment by coverney** [comment]
Sounds good. I will add in a test with the temporary TASBE Config.

**Comment by coverney** [comment]
I tried to write the test, but somehow the units change from ERF to MEFL. Can you think of any reason why? I will take a closer look at this problem next week.

**Comment by jakebeal** [comment]
I think that MEFL is what the units are supposed to be, actually --- probably it should have been complaining about ERF.

**Comment by coverney** [comment]
I ran batch analysis directly from the tutorial and the units are all ERF. Now I am trying to figure out how ERF changed to MEFL.

**Comment by coverney** [comment]
I found out the problem. It turns out that the colormodel used in the tests is in MEFL units while the colormodel used in the tutorial is in ERF units. I will change the one in the tutorial so everything is in MEFL units?

**Comment by coverney** [comment]
the test failed even though I tested it locally with Matlab and Octave and both of them passed.

**Comment by coverney** [comment]
I think the problem has something to do with the name of the point cloud file I am trying to read back in.

**Comment by jakebeal** [comment]
Fixes #415

**Pull request merged**
